version: '3'

#Use .env-documentDB file and rename it to .env

services:

  build_worker:
    image: tock/build_worker:$ENV_TAG
    environment:
      - tock_mongo_url=$ENV_MONGO_URL
      - tock_document_db_on=$ENV_MONGO_DOCDB
      - tock_env=prod
      - JAVA_ARGS=-Xmx1g -XX:MaxMetaspaceSize=256m $ENV_JAVA_ARGS
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn
    restart: always
    volumes:
      - ./ssl:/ssl
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  duckling:
    image: tock/duckling:$ENV_TAG
    environment:
      - tock_env=prod
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn
    expose:
      - "8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      mode: replicated
      replicas: 2

  kotlin_compiler:
    image: tock/kotlin_compiler:$ENV_TAG
    environment:
      - tock_env=prod
      - tock_kotlin_compiler_classpath=/maven
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn
    expose:
      - "8080"
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  admin_web:
    image: tock/bot_admin:$ENV_TAG
    depends_on:
      - duckling
      - kotlin_compiler
    environment:
      - tock_mongo_url=$ENV_MONGO_URL
      - tock_document_db_on=$ENV_MONGO_DOCDB
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_bot_admin_rest_default_base_url=http://bot_api:8080
      - tock_bot_compiler_service_url=http://kotlin_compiler:8080
      - tock_configuration_bot_default_base_url=http://bot_api:8080
      #remove this in production
      - tock_https_env=false
      - botadminverticle_body_limit=-1
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn
#      - botadminverticle_base_href=/bot/admin
      - JAVA_ARGS=$ENV_JAVA_ARGS
    ports:
      - "80:8080"
    volumes:
      - ./ssl:/ssl
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/rest/admin/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nlp_api:
    image: tock/nlp_api:$ENV_TAG
    depends_on:
      - duckling
    environment:
      - tock_mongo_url=$ENV_MONGO_URL
      - tock_document_db_on=$ENV_MONGO_DOCDB
      - nlp_duckling_url=http://duckling:8080
      - tock_env=prod
      - tock_web_use_default_cors_handler=true
      - tock_web_use_default_cors_handler_with_credentials=false
      - tock_web_use_default_cors_handler_url=*
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn
      - JAVA_ARGS=$ENV_JAVA_ARGS
    ports:
      - "8888:8080"
    volumes:
      - ./ssl:/ssl
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/rest/nlp/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      mode: replicated
      replicas: 3

  bot_api:
    image: tock/bot_api:$ENV_TAG
    depends_on:
      - nlp_api
    environment:
      - tock_mongo_url=$ENV_MONGO_URL
      - tock_document_db_on=$ENV_MONGO_DOCDB
      - tock_nlp_service_url=http://nlp_api:8080
      - tock_env=integ
      - tock_websocket_enabled=true
#      - tock_default_log_level=warn
#      - tock_service_log_level=info
#      - tock_database_log_level=warn
      - JAVA_ARGS=$ENV_JAVA_ARGS
    ports:
      - "8080:8080"
    volumes:
      - ./ssl:/ssl
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthcheck"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
